# Site settings
title: Zhaobenx' blog
header-img: img/home-bg.jpg
email: zhaobenx@outlook.com
copyright_name: Zhaobenx
description: "Personal blog"
baseurl: ""
#url: "http://yourdomain.com"
#twitter_username: SBootstrap
github_username:  zhaobenx
#facebook_username:  StartBootstrap
email_username:  zhaobenx@outlook.com
timezone: Asia/Shanghai
collections:
  words_list:
    output: false

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-104203936-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
